### ISSUE TITLE
Stack Trace when refreshing token

### ISSUE THREAD

**Issue by wwsean08** [FiniteSingularity/tau#42]
When trying to retrieve an access token via the twitch callback I am getting a key error with the following stack trace.  Not sure where to go from here on this one (also the code has been redacted from the logs).

```
Environment:


Request Method: GET
Request URL: http://tau.sean.dev/twitch-callback/?code=[CODE]&scope=bits%3Aread+channel%3Aread%3Aredemptions+channel%3Aread%3Ahype_train+channel_subscriptions

Django Version: 3.1.7
Python Version: 3.8.10
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'constance.backends.database',
 'django_extensions',
 'corsheaders',
 'channels',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'tau.users',
 'tau.core.apps.CoreConfig',
 'tau.twitchevents.apps.TwitcheventsConfig',
 'tau.streamers.apps.StreamersConfig',
 'django_nose')
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 458, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 233, in _get_response_async
    response = await wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 423, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 462, in thread_handler
    return func(*args, **kwargs)
  File "/code/./tau/core/views.py", line 167, in process_twitch_callback_view
    config.TWITCH_ACCESS_TOKEN = response_data['access_token']

Exception Type: KeyError at /twitch-callback/
Exception Value: 'access_token'
```

**Comment by FiniteSingularity** [comment]
This is happening right after TAU is attempting to get an `access_token` from the Twitch oauth2 endpoint.  The redirect page you were at right before this, required a Twitch App ID (or Client ID), a callback URI (which is properly being hit), and a scope (which is also being passed properly), so we know those values are all good.

The call to the API that is returning without an `access_token` requires the Twitch App Id, the `code` variable you redacted, and the `TWITCH_CLIENT_SECRET` value from your .env file.  So it appears that the most likely cause is either a missing, or a bad `TWITCH_CLIENT_SECRET` value in your .env file.  I'd recommend that you go to the twitch dev panel (where you originally set up the `wwsean08-tau` app), and regenerate your client secret, then paste that value back into your .env file.  Then run
`docker-compose up --build` to ensure the new environment variables are set.

**Comment by FiniteSingularity** [comment]
Fixed- @wwsean08 was using and nginx reverse proxy, and had to tweak some port settings.

**Comment by wwsean08** [comment]
For anyone that looks into this later, because of my reverse proxy I needed to change tau/config/common.py commenting out the following lines:

```python
    BASE_URL = f"{PROTOCOL}//{PUBLIC_URL}"

#    if BASE_PORT not in [80, 443]:
#        BASE_URL = BASE_URL + f":{BASE_PORT}"
```

by commenting out those 2 lines it fixed the issue.
